name: Keep Streamlit Awake

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Push Empty Commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit --allow-empty -m "Chore: Keep Streamlit app awake"
          git push
